# Generated by Django 3.2.8 on 2021-10-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('s_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('batch_no', models.CharField(max_length=50)),
            ],
        ),
    ]
