# Generated by Django 3.2.8 on 2021-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_demodatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='demodatabase',
            name='salary',
            field=models.FloatField(default=0.0, max_length=50),
        ),
    ]
