# Generated by Django 3.2.8 on 2021-11-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_demodatabase_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailDatabase07',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('s_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('batch_no', models.CharField(max_length=50)),
                ('salary', models.FloatField(default=0.0, max_length=50)),
                ('companies_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
